inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - gemfiles/vendor/**/*
    - vendor/**/*
    - ./**/*.rbx

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ArrayAlignment:
  Exclude:
    - spec/**/*_spec.rb
    - spec/test_app/app/models/**/*.rb

Layout/FirstHashElementIndentation:
  Exclude:
    - spec/**/*_spec.rb

Layout/LineLength:
  Max: 370

Lint/ConstantDefinitionInBlock: # (new in 0.91)
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

Metrics/AbcSize:
  Exclude:
    - spec/test_app/db/migrate/*
  Max: 398

Metrics/BlockLength:
  Max: 202
  Exclude:
    - spec/models/northwind_spec.rb

Metrics/BlockNesting:
  Max: 8

Metrics/ClassLength:
  Enabled: true
  Max: 227
  Exclude:
    - spec/test_app/db/migrate/*

Metrics/CyclomaticComplexity:
  Max: 122

Metrics/MethodLength:
  Max: 265
  Exclude:
    - spec/test_app/db/migrate/*
    - spec/models/northwind_spec.rb

Metrics/ModuleLength:
  Max: 484

Metrics/ParameterLists:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 137

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/*.gemfile'

# All other cops, simply to enable them:
Layout/BeginEndAlignment: # (new in 0.91)
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRequire: # (new in 0.90)
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile: # (new in 0.90)
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/HashCompareByIdentity: # (new in 0.93)
  Enabled: true

Lint/IdentityComparison: # (new in 0.91)
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantSafeNavigation: # (new in 0.93)
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition: # (new in 0.90)
  Enabled: true

Lint/UselessTimes: # (new in 0.91)
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassEqualityComparison: # (new in 0.93)
  Enabled: true

Style/CombinableLoops: # (new in 0.90)
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/KeywordParametersOrder: # (new in 0.90)
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional: # (new in 0.89)
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/SymbolArray:
  Enabled: false
